[default]
description = "Allows all MLS plugin commands"
permissions = [
    "allow-init-user",
    "allow-create-group",
    "allow-load-group",
    "allow-join-group",
    "allow-delete-group",
    "allow-encrypt",
    "allow-decrypt",
    "allow-add-member",
    "allow-export-ratchet-tree",
    "allow-create-key-package",
    "allow-extract-group-id",
    "allow-get-group-fingerprints",
    "allow-remove-group-member-client",
    "allow-remove-group-member",
    "allow-decommission-client",
    "allow-clear-all-data",
    "allow-get-own-fingerprint",
    "allow-get-key-package-fingerprint",
]
